version: '3.8'

services:
  db:
    container_name: db
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    depends_on:
      - db
    container_name: server
    image: node:14.9-alpine
    working_dir: /server
    volumes:
      - .:/server
    ports:
      - 3000:3000
      - 9229:9229
    tty: true
    command: ['/bin/sh', '-c', 'yarn && yarn dev']
